version: '3'
services:
  php:
    image: php:7.4-fpm
    container_name: php
    expose:
      - 9000
    volumes:
      - './:/var/www/html/'


  nginx:
    image: nginx:latest
    container_name: web
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - './:/var/www/html/'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'


  mariadb:
    container_name: mdb
    image: mariadb
    environment: 
      - MARIADB_ROOT_PASSWORD=$dbpass
    env_file:
      - .env



